server:
  port: 8080
  servlet:
    context-path: /votingsystem

swagger2:
  enable: true

#####################
# MyBatisµƒ≈‰÷√
#####################
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    cache-enabled: true
    call-setters-on-nulls: true

#####################
# Druidµƒ≈‰÷√
#####################
spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/votingsystem?useUnicode=true&useSSL=false&serverTimezone=GMT
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 6000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      validation-query-timeout: 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 10000
          enabled: true
        wall:
          enabled: true
          db-type: mysql
      filters: stat,wall,slf4j
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10

##############
# ∆ﬂ≈£‘∆≈‰÷√
##############
qiniu:
  access:
    key: R42l9Le3Bep-31lhlh3AQg2wpRUXJ3kaE1Tc5ccP
  secret:
    key: 9EckwTxcf5TMMFaVSwFvfLDvLnqStQBwD85talYz
  bucket:
    name: geniusdsy
    host:
      name: http://picture.geniusdsy.cn